name: Release main

on:
  push:
    branches:
      - main

jobs:
  code-checks:
    name: Run code checks and quality tools
    uses: ./.github/workflows/_code_checks.yaml

  release:
    name: Create a new production release
    needs: [code-checks]
    uses: ./.github/workflows/_sem_release.yaml
    secrets:
      semantic-release-token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
      npm-token: ${{ secrets.NPM_TOKEN }}
